/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARDUINO_PB_H_INCLUDED
#define PB_ARDUINO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Message {
    pb_callback_t description;
} Message;


/* Initializer values for message structs */
#define Message_init_default                     {{{NULL}, NULL}}
#define Message_init_zero                        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Message_description_tag                  1

/* Struct field encoding specification for nanopb */
#define Message_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   description,       1)
#define Message_CALLBACK pb_default_field_callback
#define Message_DEFAULT NULL

extern const pb_msgdesc_t Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Message_fields &Message_msg

/* Maximum encoded size of messages (where known) */
/* Message_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
