/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "arduino_reply.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ArduinoReply, ArduinoReply, AUTO)


PB_BIND(ArduinoReply_WifiScanResult, ArduinoReply_WifiScanResult, AUTO)


PB_BIND(ArduinoReply_BatteryResult, ArduinoReply_BatteryResult, AUTO)




