/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARDUINO_PB_H_INCLUDED
#define PB_ARDUINO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Message {
    int32_t uniqueId;
} Message;


/* Initializer values for message structs */
#define Message_init_default                     {0}
#define Message_init_zero                        {0}

/* Field tags (for use in manual encoding/decoding) */
#define Message_uniqueId_tag                     1

/* Struct field encoding specification for nanopb */
#define Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    uniqueId,          1)
#define Message_CALLBACK NULL
#define Message_DEFAULT NULL

extern const pb_msgdesc_t Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Message_fields &Message_msg

/* Maximum encoded size of messages (where known) */
#define Message_size                             11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
